eventManager/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin

app_name='eventManager'

urlpatterns=[
    #rest-api urls
    url(r'^teachers/$', views.TeacherList.as_view()),
    url(r'^students/$', views.StudentList.as_view()),
    url(r'^teachers/(?P<pk>[0-9]+)/$', views.EventDetail.as_view()),
    #url(r'^students/(?P<pk>[0-9]+)/$', views.RegisteredEvents.as_view()),
    #normal urls
    url(r'^$',views.index,name="index"),
    url(r'^teacherLogin/$',views.TeacherLogin,name="teacherLogin"),
    url(r'^studentLogin/$',views.StudentLogin,name="studentLogin"),
    url(r'^teacherLogin/teacherLoginForm',views.teacherLoginForm,name="teacherLoginForm"),
   # url(r'^teacherLogin/(?P<pk>[0-9]+)$', views.teacherLoggedIn, name="teacherLoggedIn"),
    url(r'^admin/adminLogin', views.AdminLogin, name="adminLogin"),
    #url(r'^admin/adminLogin/teacherRegister/$',views.TeacherFormView,name="teacherRegister"),
   # url(r'^ajaxtest/$',views.ajaxtest,name="test"),
    #url(r'^teacherLogin/(?P<pk>[0-9]+)$', views.detail.as_view(), name="teacherLoggedIn"),
    url(r'^teacherLogin/(?P<pk>[0-9]+)/$', views.teacherOptions, name="teacherOptions"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/createEvent/$', views.CreateEvent.as_view(), name="createEvent"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/viewMyEvents/$', views.viewMyEvents.as_view(), name="viewMyEvents"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/viewAllEvents/$', views.viewAllEvents.as_view(), name="viewAllEvents"),

    url(r'^teacherLogin/(?P<dept>[a-zA-Z]+)/facultyList/$',views.FacultyList.as_view(),name="facultyList"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/viewDetailsT/$', views.ViewDetailsT.as_view(), name="viewDetailsT"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/createEvent/invalidTime/$', views.InvalidTime.as_view(), name="invalidTime"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/createEvent/invalidDate/$', views.InvalidDate.as_view(), name="invalidDate"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/createEvent/createEventSuccess/$', views.CreateEventSuccess.as_view(), name="createEventSuccess"),
    url(r'^teacherLogin/(?P<id>[0-9]+)/createEvent/createEventFailure/$', views.CreateEventFailure.as_view(), name="createEventFailure"),
    url(r'^about/$',views.About.as_view(),name="about"),

    #students
    url(r'^studentLogin/$',views.StudentLogin,name="studentLogin"),
    url(r'^studentLogin/(?P<pk>[0-9]+)/$', views.studentOptions, name="studentOptions"),
    url(r'^studentLogin/(?P<id>[0-9]+)/viewAllEventsS/$', views.viewAllEventsS.as_view(), name="viewAllEventsS"),
    url(r'^studentLogin/(?P<id>[0-9]+)/viewMyDeptEvents/$', views.viewMyDeptEvents.as_view(), name="viewMyDeptEvents"),
    url(r'^studentLogin/(?P<id>[0-9]+)/viewMyEventsS/$', views.viewMyEventsS.as_view(), name="viewMyEventsS"),
    url(r'^studentLogin/(?P<id>[0-9]+)/registerEvent/$', views.registerEvent.as_view(), name="registerEvent"),
    url(r'^studentLogin/(?P<id>[0-9]+)/registerEvent/(?P<eid>[0-9]+)/$', views.eventRegistered.as_view(), name="eventRegistered"),
    url(r'^studentLogin/(?P<id>[0-9]+)/givefeedback/(?P<eid>[0-9]+)/$', views.Feedback.as_view(), name="feedback"),
    url(r'^studentLogin/(?P<id>[0-9]+)/givefeedback/$', views.GiveFeedback.as_view(), name="givefeedback"),
    url(r'^studentLogin/(?P<id>[0-9]+)/givefeedback/invalidFeedback$', views.InvalidFeedback.as_view(), name="invalidFeedback"),
    url(r'^studentLogin/(?P<id>[0-9]+)/feedbackSuccess/$', views.FeedbackSuccess.as_view(), name="feedbackSuccess"),
    url(r'^studentLogin/(?P<id>[0-9]+)/viewDetailsS/$', views.ViewDetailsS.as_view(), name="viewDetailsS"),

    #admin
    url(r'^adminLogin/$', views.adminLoginForm, name="adminLogin"),
    url(r'^adminLogin/(?P<pk>[0-9]+)/$', views.adminOptions, name="adminOptions"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerTeacher/$', views.RegisterTeacher.as_view(), name="registerTeacher"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerTeacher/teacherRegisterSuccess/$', views.TeacherRegisterSuccess.as_view(), name="teacherRegisterSuccess"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerTeacher/teacherRegisterFailure/$', views.TeacherRegisterFailure.as_view(),name="teacherRegisterFailure"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerTeacher/teacherinvalidDept/$', views.TeacherInvalidDept.as_view(),name="teacherinvalidDept"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerTeacher/teacherAlreadyExists/$', views.TeacherAlreadyExists.as_view(),name="teacherAlreadyExists"),

    url(r'^adminLogin/(?P<id>[0-9]+)/registerStudent/$', views.RegisterStudent.as_view(), name="registerStudent"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerStudent/studentRegisterSuccess/$', views.StudentRegisterSuccess.as_view(),name="studentRegisterSuccess"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerStudent/studentRegisterFailure/$', views.StudentRegisterFailure.as_view(),name="studentRegisterFailure"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerStudent/studentAlreadyExists/$', views.StudentAlreadyExists.as_view(),name="studentAlreadyExists"),
    url(r'^adminLogin/(?P<id>[0-9]+)/registerStudent/studentinvalidDept/$', views.StudentInvalidDept.as_view(), name="StudentinvalidDept"),

]

eventManagerProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^eventManager/', include("eventManager.urls")),



]

eventManager/forms.py
from django.forms.models import ModelForm
from django import forms

from eventManager.models import *


class TeacherForm(ModelForm):
    class Meta:
        model=Teacher
        fields = ('teacherName',  'teacherPassword','teacherDept','teacherExperience')

class StudentForm(ModelForm):
    studentPassword = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=Student
        fields=('studentRollNumber','studentName','studentPassword','studentDept','studentCGPA','studentAttendance')

class EventForm(ModelForm):
    class Meta:
        model=Event
        fields=('eventName','resourcePerson','eventDate','eventStartTime','eventEndTime','eventVenue','ECE','CSE','EEE','IT','mechanical','chemical','civil')

class FeedbackForm(ModelForm):
    class Meta:
        model = RegisteredEvents
        fields = ('eventRating','teacherCredits')

class AdminForm(ModelForm):
    adminPassword=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=Admin
        fields=('adminName','adminPassword')

eventManager/views.py
from django.http.response import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from .models import*
from .serializers import *
from rest_framework import generics
from django.template import loader
from django.views.generic.list import ListView
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
import json
from .forms import *
import datetime

# Create your views here.
from eventManager.models import *
from eventManager.serializers import *

#rest api  views
class TeacherList(generics.ListCreateAPIView):
    queryset = Teacher.objects.all()
    serializer_class = TeacherSerializer

class StudentList(generics.ListCreateAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer


class EventDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

'''class RegisteredEvents(generics.ListAPIView):
    queryset = RegisteredEvents.objects.all()
    serializer_class = RegisteredEventsSerializer'''

#normal views
def index(request):
    template='eventManager/index.html'
    return render(request,template)

def TeacherLogin(request):
    template = 'eventManager/teacherLogin.html'
    return render(request, template)

'''def StudentLogin(request):
    template = 'eventManager/studentLogin.html'
    return render(request, template)'''

def AdminLogin(request):
    template='eventManager/adminLogin.html'
    return render(request,template)

class About(ListView):
    model=Teacher
    template_name="eventManager/aboutTheApp.html"

class FacultyList(ListView):
    model=Teacher
    template_name="eventManager/facultyList.html"
    context_object_name="faculty"

    def get_queryset(self):
        return Teacher.objects.filter(teacherDept=self.kwargs['dept'])

    def get_context_data(self, **kwargs):
        context = super(FacultyList, self).get_context_data(**kwargs)
        context['dept'] = self.kwargs['dept']
        return context


def teacherLoginForm(request):
    if request.method == 'POST':
        #POST goes here . is_ajax is must to capture ajax requests. Beginner's pit.
        if request.is_ajax():
            userName = request.POST.get('userName')
            password = request.POST.get('password')

            querySet=Teacher.objects.filter(teacherName=userName,teacherPassword=password)
            #converts query set to string in json format
            data=json.dumps([dict(item) for item in Teacher.objects.filter(teacherName=userName,teacherPassword=password).values('id','teacherName', 'teacherPassword')])

            return JsonResponse(data,safe=False)
            #else : return HttpResponseRedirect('teacherLoginForm'+str(querySet[0].id))
    #Get goes here
    return render(request,'eventManager/teacherLoginForm.html')

def teacherLoggedIn(request,id):
    template = 'eventManager/index.html'
    return render(request, template)

'''class detail(DetailView):
    model=Event
    template_name = 'eventManager/events.html'
    context_object_name = "events"'''

def teacherOptions(request,pk):
    querySet = Event.objects.filter(id=pk)
    template = 'eventManager/teacherOptions.html'
    return render(request, template)

class CreateEvent(View):

    form_class = EventForm
    template_name = 'eventManager/eventForm.html'

    def get(self, request,id):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request,id):
        form = self.form_class(request.POST)

        if form.is_valid():
            # creats an object of form but doesnot save into database
            event = form.save(commit=False)
            # cleaned (normalized) data

            eventName = form.cleaned_data['eventName']
            resourcePerson = form.cleaned_data['resourcePerson']
            eventVenue = form.cleaned_data['eventVenue']
            ECE = form.cleaned_data['ECE']
            CSE = form.cleaned_data['CSE']
            EEE = form.cleaned_data['EEE']
            IT = form.cleaned_data['IT']
            mechanical = form.cleaned_data['mechanical']
            chemical = form.cleaned_data['chemical']
            civil = form.cleaned_data['civil']
            eventDate = form.cleaned_data['eventDate']

            todayDate=datetime.datetime.now().date()
            if(eventDate<=todayDate):
                return redirect('/eventManager/teacherLogin/%i/createEvent/invalidDate/' % int(id))

            eventStartTime = form.cleaned_data['eventStartTime']
            eventEndTime = form.cleaned_data['eventEndTime']
            if(eventStartTime>=eventEndTime):
                return redirect('/eventManager/teacherLogin/%i/createEvent/invalidTime/' % int(id))

            t=Teacher.objects.filter(id=self.kwargs['id'])

            event.teacher=t[0]

            event.save()

            #return redirect('eventDetail/%i/' % event.id)
            return redirect('/eventManager/teacherLogin/%i/createEvent/createEventSuccess/' % int(id))
        return redirect('/eventManager/teacherLogin/%i/createEvent/createEventFailure/' % int(id))

class InvalidTime(ListView):
    model=Event
    template_name='eventManager/invalidTime.html'

    def get_context_data(self, **kwargs):
        context = super(InvalidTime, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

class InvalidDate(ListView):
    model=Event
    template_name='eventManager/invalidDate.html'

    def get_context_data(self, **kwargs):
        context = super(InvalidDate, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

class CreateEventSuccess(ListView):
    model=Teacher
    template_name='eventManager/createEventSuccess.html'

    def get_context_data(self, **kwargs):
        context = super(CreateEventSuccess, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

class CreateEventFailure(ListView):
    model=Teacher
    template_name='eventManager/createEventFailure.html'

    def get_context_data(self, **kwargs):
        context = super(CreateEventFailure, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

class viewMyEvents(ListView):
    model=Event
    template_name="eventManager/viewMyEvents.html"
    context_object_name="myEvents"

    def get_queryset(self):
        return Event.objects.filter(teacher_id=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super(viewMyEvents, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

class viewAllEvents(ListView):
    model=Event
    template_name="eventManager/viewAllEvents.html"
    context_object_name="allEvents"

    def get_queryset(self):
        return Event.objects.all()

    def get_context_data(self, **kwargs):
        context = super(viewAllEvents, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

class ViewDetailsT(ListView):

    model = Teacher
    template_name = 'eventManager/viewDetailsT.html'
    context_object_name = "teacher"

    def get_queryset(self):
        return Teacher.objects.filter(id=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super(ViewDetailsT, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

#student
def StudentLogin(request):
    if request.method == 'POST':
        # POST goes here . is_ajax is must to capture ajax requests. Beginner's pit.
        if request.is_ajax():
            userName = request.POST.get('userName')
            password = request.POST.get('password')

            querySet = Teacher.objects.filter(teacherName=userName, teacherPassword=password)
            # converts query set to string in json format
            data = json.dumps([dict(item) for item in
                               Student.objects.filter(studentRollNumber=userName, studentPassword=password).values('id',
                                                                                                             'studentName',
                                                                                                             'studentPassword')])

            return JsonResponse(data, safe=False)
            # else : return HttpResponseRedirect('teacherLoginForm'+str(querySet[0].id))
    # Get goes here
    return render(request, 'eventManager/studentLogin.html')

def studentOptions(request,pk):
    querySet = Event.objects.filter(id=pk)
    template = 'eventManager/studentOptions.html'
    return render(request, template)

class viewMyDeptEvents(ListView):
    model=Event
    template_name="eventManager/viewMyDeptEvents.html"
    context_object_name="myEvents"

    def get_queryset(self):
        q=Student.objects.filter(id=self.kwargs['id']).values('studentDept')
        s=q[0].values()
        dept=s[0].encode('iso-8859-1')
        if(dept=='CSE'):
            return Event.objects.filter(CSE=True)
        if (dept == 'ECE'):
            return Event.objects.filter(ECE=True)
        if (dept == 'EEE'):
            return Event.objects.filter(EEE=True)
        if (dept == 'IT'):
            return Event.objects.filter(IT=True)
        if (dept == 'mechanical'):
            return Event.objects.filter(mechanical=True)
        if (dept == 'chemical'):
            return Event.objects.filter(chemical=True)
        if (dept == 'civil'):
            return Event.objects.filter(civil=True)

    def get_context_data(self, **kwargs):
        context = super(viewMyDeptEvents, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        return context

eventManager/templates/eventManager/createEventSuccess.html
<html >
    <head>
        {% load staticfiles %}
        {% load admin_urls %}
        <title>{% block title %}create-event-success{% endblock %}</title>
        <!--to work for any view port-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--loads path to static files-->

        <link rel="stylesheet" type="text/css" href="{% static "eventManager/style.css"%}"/>
        <link rel="stylesheet" type="text/css" href="{% static "eventManager/css/bootstrap.min.css"%}"/>
        <script src="{% static "eventManager/jquery.js"%}"></script>
        <script src="{% static "eventManager/js/bootstrap.min.js"%}"></script>
    </head>
    <body>
        <div class="jumbotron" style="background-color:#0AC9B2;width:100%;padding:3%">
               <div class ="text-center" style="align:center; font-size: 300%;color:#F8FBFC;"> ANITS EVENT MANAGER</div>
        </div>
        <div align="center">
            <h3>You have successfully created an event</h3>
        </div>
        <br><br><br>
        <div align="center">
            <button type = "button" class = "btn btn-primary btn-lg" onclick="location.href='/eventManager/teacherLogin/{{ id}}/' ">
                        ok
            </button>
        </div>
    </body>
</html>

eventManager/templates/eventManager/studentLogin.html
<html>
    <head>
        {% load staticfiles %}
        {% load admin_urls %}
        <title>{% block title %}student-login-form{% endblock %}</title>
        <!--to work for any view port-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--loads path to static files-->

        <link rel="stylesheet" type="text/css" href="{% static "eventManager/style.css"%}"/>
        <link rel="stylesheet" type="text/css" href="{% static "eventManager/signin.css"%}"/>
        <link rel="stylesheet" type="text/css" href="{% static "eventManager/css/bootstrap.min.css"%}"/>
        <script src="{% static "eventManager/jquery.js"%}"></script>
        <script src="{% static "eventManager/js/bootstrap.min.js"%}"></script>
    </head>
    <body>
        <div class="jumbotron" style="background-color:#0AC9B2;width:100%;padding:3%;margin:0;">
               <div class ="text-center" style="align:center; font-size: 300%;color:#F8FBFC;"> ANITS EVENT MANAGER</div>
        </div>

        <div class="container-fluid" style="padding: 10%;">
        <form class="form-signin" method="POST">
            {% csrf_token %}
            <!--<h2 class="Enter Details" style="align:center;">Enter Details</h2>-->
            <div class="text-center" style="font-size: 230%;">Enter Details</div><br><br>
             <label for="inputUserName" class="sr-only">Roll Number</label>
             <input type="text" id="inputUserName" class="form-control" placeholder="roll number" required autofocus>
             <label for="inputPassword" class="sr-only">Password</label>
             <input type="password" id="inputPassword" class="form-control"  placeholder="Password" required>
             <button id="submit" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
        </div>
        <div id="success_div"></div>
       <script>

        //For getting CSRF token
        function getCookie(name) {
               var cookieValue = null;
               if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                 var cookie = jQuery.trim(cookies[i]);
                 // Does this cookie string begin with the name we want?
                 if (cookie.substring(0, name.length + 1) == (name + '=')) {
                     cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                     break;
                  }
             }
         }
         return cookieValue;
        }

        $(".form-signin").submit(function(e) {

         e.preventDefault();

         var csrftoken = getCookie('csrftoken');

         var userName = $('#inputUserName').val();

         var password = $('#inputPassword').val();

        //This is the Ajax post.Observe carefully. It is nothing but details of where_to_post,what_to_post
         $.ajax({
                 url : window.location.href, // the endpoint,commonly same url
                 type : "POST", // http method
                 data : { csrfmiddlewaretoken : csrftoken,
                 userName : userName,
                 password : password
         }, // data sent with the post request

         // handle a successful response
         success : function(json) {

              obj=JSON.parse(json)
             console.log(json);
              if(obj.length===0) {
                  window.alert("enter valid credentails");
              }
             else
                     window.location.href='{% url "eventManager:studentOptions" 0 %}'.replace('0', obj[0].id);
         },

         // handle a non-successful response
         error : function(xhr,errmsg,err) {
         console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
         }
         });
        });

        </script>

    </body>
</html>

eventManager/templates/eventManager/teacherLogin.html
<html >
    <head>
        {% load staticfiles %}
        {% load admin_urls %}
        <title>{% block title %}teacher-login{% endblock %}</title>
        <!--to work for any view port-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--loads path to static files-->

        <link rel="stylesheet" type="text/css" href="{% static "eventManager/style.css"%}"/>
        <link rel="stylesheet" type="text/css" href="{% static "eventManager/css/bootstrap.min.css"%}"/>
        <script src="{% static "eventManager/jquery.js"%}"></script>
        <script src="{% static "eventManager/js/bootstrap.min.js"%}"></script>
    </head>
    <body>
        <div class="jumbotron" style="background-color:#0AC9B2;width:100%;padding:3%">
               <div class ="text-center" style="align:center; font-size: 300%;color:#F8FBFC;"> ANITS EVENT MANAGER</div>
        </div>
        <div class="container-fluid">
            <div class="text-center" style="font-size:175%">Click on any department to view its faculty</div><br>
            <div class="row">
                <div class =col-md-3>
                    <a class="thumbnail" onclick="location.href='CSE/facultyList'">
                    <img class="img-responsive" id="img" src="{% static "eventManager/images/cse-image.jpg"%}" alt="">
                </a>
                </div>
                <div class =col-md-3>
                    <a class="thumbnail"  onclick="location.href='ECE/facultyList'">
                    <img class="img-responsive" id="img" src="{% static "eventManager/images/Electronics-communication.jpg"%}" alt="">
                </a>
                </div>
                <div class =col-md-3>
                    <a class="thumbnail" onclick="location.href='EEE/facultyList'">
                    <img class="img-responsive" id="img" src="{% static "eventManager/images/electrical-electronics-engineering-EEE-image.jpg"%}" alt="">
                </a>
                </div>
                <div class =col-md-offset-3>
                    <br><br>
                    <div class="text-center"  style="font-size:175%">Click the below button to login</div><br>
                    <div align="center" >
                    <button type = "button" class = "btn btn-primary btn-lg" styles="padding:0px;" onclick="location.href='{%  url "eventManager:teacherLoginForm"  %}'">
                        Login
                    </button>
                    </div>
                </div>

            </div>
            <br><br>
             <div class="row">
                <div class =col-md-3>
                    <a class="thumbnail" onclick="location.href='civil/facultyList'">
                    <img class="img-responsive" id="img" src="{% static "eventManager/images/CEcover.jpg"%}" alt="">
                </a>
                </div>
                <div class =col-md-3>
                    <a class="thumbnail"onclick="location.href='mechanical/facultyList'">
                    <img class="img-responsive" id="cse" src="{% static "eventManager/images/download.jpg"%}" alt="">
                </a>
                </div>
                <div class =col-md-3>
                    <a class="thumbnail"onclick="location.href='IT/facultyList'">
                    <img class="img-responsive" id="img" src="{% static "eventManager/images/information-technology.jpg"%}" alt="">
                </a>
                </div>

                <div class =col-md-3>
                    <a class="thumbnail" onclick="location.href='chemical/facultyList'">
                    <img class="img-responsive" id="img" src="{% static "eventManager/images/Master-program-Chemical-Engineering-distance-education.jpg"%}" alt="">
                </a>
                </div>
            </div>

        </div>
    </body>

</html>

eventManager/templates/eventManager/teacherLoginForm.html
<html>
    <head>
        {% load staticfiles %}
        {% load admin_urls %}
        <title>{% block title %}teacher-login-form{% endblock %}</title>
        <!--to work for any view port-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--loads path to static files-->

        <link rel="stylesheet" type="text/css" href="{% static "eventManager/style.css"%}"/>
        <link rel="stylesheet" type="text/css" href="{% static "eventManager/signin.css"%}"/>
        <link rel="stylesheet" type="text/css" href="{% static "eventManager/css/bootstrap.min.css"%}"/>
        <script src="{% static "eventManager/jquery.js"%}"></script>
        <script src="{% static "eventManager/js/bootstrap.min.js"%}"></script>
    </head>
    <body>
        <div class="jumbotron" style="background-color:#0AC9B2;width:100%;padding:3%;margin:0;">
               <div class ="text-center" style="align:center; font-size: 300%;color:#F8FBFC;"> ANITS EVENT MANAGER</div>
        </div>

        <div class="container-fluid" style="padding: 10%;">
        <form class="form-signin" method="POST">
            {% csrf_token %}
            <!--<h2 class="Enter Details" style="align:center;">Enter Details</h2>-->
            <div class="text-center" style="font-size: 230%;">Enter Details</div><br><br>
             <label for="inputUserName" class="sr-only">User Name</label>
             <input type="text" id="inputUserName" class="form-control" placeholder="user name" required autofocus>
             <label for="inputPassword" class="sr-only">Password</label>
             <input type="password" id="inputPassword" class="form-control"  placeholder="Password" required>
             <button id="submit" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
        </div>
        <div id="success_div"></div>
       <script>

        //For getting CSRF token
        function getCookie(name) {
               var cookieValue = null;
               if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                 var cookie = jQuery.trim(cookies[i]);
                 // Does this cookie string begin with the name we want?
                 if (cookie.substring(0, name.length + 1) == (name + '=')) {
                     cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                     break;
                  }
             }
         }
         return cookieValue;
        }

        $(".form-signin").submit(function(e) {

         e.preventDefault();

         var csrftoken = getCookie('csrftoken');

         var userName = $('#inputUserName').val();

         var password = $('#inputPassword').val();

        //This is the Ajax post.Observe carefully. It is nothing but details of where_to_post,what_to_post
         $.ajax({
                 url : window.location.href, // the endpoint,commonly same url
                 type : "POST", // http method
                 data : { csrfmiddlewaretoken : csrftoken,
                 userName : userName,
                 password : password
         }, // data sent with the post request

         // handle a successful response
         success : function(json) {

              obj=JSON.parse(json)
             console.log(json);
              if(obj.length===0) {
                  window.alert("enter valid credentails");
              }
             else
                     window.location.href='{% url "eventManager:teacherOptions" 0 %}'.replace('0', obj[0].id);
         },

         // handle a non-successful response
         error : function(xhr,errmsg,err) {
         console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
         }
         });
        });

        </script>

    </body>
</html>